name: js_unpack
description: Unpacks P.A.C.K.E.R. packed js code. / generate javascript code from packed js code.
version: 1.0.2
repository: https://github.com/linkkader/js_unpack

# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
